In [2]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
import matplotlib.pyplot as plt
import seaborn as sns
import time
import re

# 1. Combine three datasets downloaded from Yelp

## Summary
## Combine three datasets downloaded from Yelp 
## Select only opened-restaurant businesses

## 1.1. Combine three datasets

In [62]:
user_data = pd.read_csv('user_dataset_updated1.csv', encoding = 'utf-8')
#review_data = pd.read_csv('review_dataset.csv', encoding = 'utf-8')

#business_data = pd.read_csv('business_dataset.csv', encoding = 'utf-8')

In [12]:
review_data = pd.read_csv('review_dataset.csv', encoding = 'utf-8')

In [13]:
review_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8635387 entries, 0 to 8635386
Data columns (total 7 columns):
 #   Column       Dtype
---  ------       -----
 0   ReviewId     object
 1   Business ID  object
 2   user_id      object
 3   useful       int64
 4   stars        float64
 5   date         object
 6   review_text  object
dtypes: float64(1), int64(1), object(5)
memory usage: 461.2+ MB

In [21]:
sorted(review_data['date'],reverse= True)

['2021-01-28 15:38:54',
 '2021-01-28 15:38:04',
 '2021-01-28 15:37:16',
 '2021-01-28 15:36:31',
 '2021-01-28 15:35:51',
 '2021-01-28 15:35:20',
 '2021-01-28 15:34:59',
 '2021-01-28 15:32:57',
 '2021-01-28 15:31:41',
 '2021-01-28 15:31:19',
 '2021-01-28 15:31:01',
 '2021-01-28 15:30:21',
 '2021-01-28 15:29:09',
 '2021-01-28 15:28:16',
 '2021-01-28 15:28:09',
 '2021-01-28 15:27:47',
 '2021-01-28 15:27:21',
 '2021-01-28 15:27:04',
 '2021-01-28 15:25:55',
 '2021-01-28 15:25:31',
 '2021-01-28 15:25:19',
 '2021-01-28 15:24:45',
 '2021-01-28 15:24:23',
 '2021-01-28 15:23:52',
 '2021-01-28 15:23:27',
 '2021-01-28 15:23:13',
 '2021-01-28 15:22:48',
 '2021-01-28 15:22:42',
 '2021-01-28 15:21:57',
 '2021-01-28 15:21:24',
 '2021-01-28 15:21:23',
 '2021-01-28 15:20:55',
 '2021-01-28 15:20:51',
 '2021-01-28 15:20:04',
 '2021-01-28 15:19:59',
 '2021-01-28 15:19:14',
 '2021-01-28 15:19:09',
 '2021-01-28 15:19:07',
 '2021-01-28 15:19:01',
 '2021-01-28 15:18:34',
 '2021-01-28 15:18:00',
 '2021-01-28 15:17:39',
 '2021-01-28 15:16:45',
 '2021-01-28 15:15:29',
 '2021-01-28 15:14:39',
 '2021-01-28 15:14:21',
 '2021-01-28 15:13:00',
 '2021-01-28 15:10:04',
 '2021-01-28 15:09:56',
 '2021-01-28 15:09:31',
 '2021-01-28 15:09:26',
 '2021-01-28 15:08:08',
 '2021-01-28 15:07:18',
 '2021-01-28 15:07:09',
 '2021-01-28 15:05:19',
 '2021-01-28 15:04:28',
 '2021-01-28 15:04:10',
 '2021-01-28 15:03:38',
 '2021-01-28 15:03:37',
 '2021-01-28 15:03:13',
 '2021-01-28 15:02:58',
 '2021-01-28 15:02:08',
 '2021-01-28 15:01:50',
 '2021-01-28 15:01:18',
 '2021-01-28 14:57:56',
 '2021-01-28 14:56:41',
 '2021-01-28 14:56:22',
 '2021-01-28 14:55:13',
 '2021-01-28 14:54:58',
 '2021-01-28 14:54:50',
 '2021-01-28 14:54:20',
 '2021-01-28 14:53:51',
 '2021-01-28 14:53:48',
 '2021-01-28 14:53:30',
 '2021-01-28 14:52:47',
 '2021-01-28 14:52:10',
 '2021-01-28 14:51:18',
 '2021-01-28 14:51:09',
 '2021-01-28 14:50:43',
 '2021-01-28 14:50:24',
 '2021-01-28 14:47:50',
 '2021-01-28 14:47:40',
 '2021-01-28 14:47:29',
 '2021-01-28 14:47:25',
 '2021-01-28 14:44:21',
 '2021-01-28 14:43:54',
 '2021-01-28 14:42:26',
 '2021-01-28 14:41:31',
 '2021-01-28 14:39:58',
 '2021-01-28 14:39:51',
 '2021-01-28 14:38:42',
 '2021-01-28 14:38:39',
 '2021-01-28 14:36:27',
 '2021-01-28 14:36:08',
 '2021-01-28 14:35:41',
 '2021-01-28 14:35:30',
 '2021-01-28 14:35:30',
 '2021-01-28 14:34:32',
 '2021-01-28 14:33:38',
 '2021-01-28 14:33:05',
 '2021-01-28 14:32:25',
 '2021-01-28 14:32:15',
 '2021-01-28 14:32:12',
 '2021-01-28 14:31:59',
 '2021-01-28 14:30:34',
 '2021-01-28 14:28:04',
 '2021-01-28 14:27:19',
 '2021-01-28 14:26:48',
 '2021-01-28 14:26:27',
 '2021-01-28 14:25:12',
 '2021-01-28 14:22:51',
 '2021-01-28 14:22:46',
 '2021-01-28 14:21:28',
 '2021-01-28 14:20:40',
 '2021-01-28 14:20:13',
 '2021-01-28 14:20:05',
 '2021-01-28 14:19:38',
 '2021-01-28 14:19:27',
 '2021-01-28 14:18:14',
 '2021-01-28 14:17:33',
 '2021-01-28 14:16:56',
 '2021-01-28 14:16:22',
 '2021-01-28 14:15:53',
 '2021-01-28 14:15:29',
 '2021-01-28 14:15:08',
 '2021-01-28 14:14:23',
 '2021-01-28 14:14:04',
 '2021-01-28 14:14:01',
 '2021-01-28 14:12:48',
 '2021-01-28 14:12:40',
 '2021-01-28 14:11:31',
 '2021-01-28 14:11:17',
 '2021-01-28 14:09:19',
 '2021-01-28 14:08:49',
 '2021-01-28 14:08:40',
 '2021-01-28 14:07:47',
 '2021-01-28 14:05:59',
 '2021-01-28 14:04:17',
 '2021-01-28 14:04:07',
 '2021-01-28 14:03:36',
 '2021-01-28 14:02:03',
 '2021-01-28 14:01:06',
 '2021-01-28 13:59:55',
 '2021-01-28 13:57:11',
 '2021-01-28 13:55:55',
 '2021-01-28 13:55:24',
 '2021-01-28 13:54:35',
 '2021-01-28 13:53:03',
 '2021-01-28 13:51:35',
 '2021-01-28 13:48:40',
 '2021-01-28 13:47:15',
 '2021-01-28 13:46:53',
 '2021-01-28 13:46:33',
 '2021-01-28 13:45:40',
 '2021-01-28 13:43:11',
 '2021-01-28 13:42:47',
 '2021-01-28 13:42:28',
 '2021-01-28 13:40:31',
 '2021-01-28 13:36:24',
 '2021-01-28 13:30:54',
 '2021-01-28 13:30:50',
 '2021-01-28 13:29:28',
 '2021-01-28 13:25:44',
 '2021-01-28 13:24:58',
 '2021-01-28 13:24:29',
 '2021-01-28 13:24:25',
 '2021-01-28 13:23:56',
 '2021-01-28 13:22:34',
 '2021-01-28 13:20:39',
 '2021-01-28 13:20:08',
 '2021-01-28 13:19:26',
 '2021-01-28 13:18:18',
 '2021-01-28 13:11:50',
 '2021-01-28 13:09:45',
 '2021-01-28 13:03:51',
 '2021-01-28 12:58:48',
 '2021-01-28 12:56:34',
 '2021-01-28 12:54:14',
 '2021-01-28 12:54:03',
 '2021-01-28 12:52:33',
 '2021-01-28 12:51:04',
 '2021-01-28 12:49:37',
 '2021-01-28 12:49:12',
 '2021-01-28 12:48:14',
 '2021-01-28 12:47:17',
 '2021-01-28 12:46:51',
 '2021-01-28 12:43:49',
 '2021-01-28 12:40:59',
 '2021-01-28 12:36:29',
 '2021-01-28 12:32:52',
 '2021-01-28 12:31:52',
 '2021-01-28 12:28:52',
 '2021-01-28 12:28:30',
 '2021-01-28 12:25:20',
 '2021-01-28 12:21:37',
 '2021-01-28 12:21:22',
 '2021-01-28 12:21:17',
 '2021-01-28 12:19:42',
 '2021-01-28 12:18:33',
 '2021-01-28 12:16:10',
 '2021-01-28 12:15:31',
 '2021-01-28 12:14:09',
 '2021-01-28 12:13:53',
 '2021-01-28 12:11:55',
 '2021-01-28 12:09:36',
 '2021-01-28 12:06:41',
 '2021-01-28 12:04:54',
 '2021-01-28 12:03:50',
 '2021-01-28 11:59:26',
 '2021-01-28 11:59:03',
 '2021-01-28 11:58:36',
 '2021-01-28 11:58:18',
 '2021-01-28 11:57:05',
 '2021-01-28 11:56:17',
 '2021-01-28 11:46:00',
 '2021-01-28 11:44:03',
 '2021-01-28 11:37:46',
 '2021-01-28 11:33:30',
 '2021-01-28 11:29:02',
 '2021-01-28 11:28:13',
 '2021-01-28 11:23:36',
 '2021-01-28 11:15:33',
 '2021-01-28 11:08:30',
 '2021-01-28 11:01:28',
 '2021-01-28 10:59:36',
 '2021-01-28 10:47:07',
 '2021-01-28 10:44:40',
 '2021-01-28 10:42:39',
 '2021-01-28 10:38:26',
 '2021-01-28 10:27:57',
 '2021-01-28 10:25:07',
 '2021-01-28 10:19:51',
 '2021-01-28 10:08:51',
 '2021-01-28 10:03:11',
 '2021-01-28 10:00:38',
 '2021-01-28 09:58:32',
 '2021-01-28 09:53:52',
 '2021-01-28 09:51:10',
 '2021-01-28 09:50:01',
 '2021-01-28 09:40:17',
 '2021-01-28 09:40:10',
 '2021-01-28 09:37:47',
 '2021-01-28 09:28:24',
 '2021-01-28 09:25:22',
 '2021-01-28 09:22:42',
 '2021-01-28 09:19:31',
 '2021-01-28 09:17:46',
 '2021-01-28 09:17:29',
 '2021-01-28 09:16:57',
 '2021-01-28 09:15:44',
 '2021-01-28 09:12:52',
 '2021-01-28 09:08:25',
 '2021-01-28 09:08:21',
 '2021-01-28 09:08:12',
 '2021-01-28 09:06:48',
 '2021-01-28 09:02:41',
 '2021-01-28 08:58:24',
 '2021-01-28 08:49:21',
 '2021-01-28 08:48:53',
 '2021-01-28 08:45:48',
 '2021-01-28 08:44:57',
 '2021-01-28 08:43:15',
 '2021-01-28 08:40:05',
 '2021-01-28 08:38:22',
 '2021-01-28 08:37:22',
 '2021-01-28 08:36:39',
 '2021-01-28 08:36:03',
 '2021-01-28 08:31:42',
 '2021-01-28 08:30:35',
 '2021-01-28 08:26:32',
 '2021-01-28 08:20:20',
 '2021-01-28 08:16:07',
 '2021-01-28 08:15:36',
 '2021-01-28 08:11:15',
 '2021-01-28 08:10:34',
 '2021-01-28 08:08:50',
 '2021-01-28 08:08:50',
 '2021-01-28 08:06:12',
 '2021-01-28 08:04:11',
 '2021-01-28 07:56:22',
 '2021-01-28 07:51:48',
 '2021-01-28 07:51:46',
 '2021-01-28 07:49:43',
 '2021-01-28 07:49:24',
 '2021-01-28 07:47:41',
 '2021-01-28 07:46:57',
 '2021-01-28 07:45:47',
 '2021-01-28 07:39:02',
 '2021-01-28 07:36:00',
 '2021-01-28 07:33:35',
 '2021-01-28 07:32:27',
 '2021-01-28 07:24:44',
 '2021-01-28 07:23:47',
 '2021-01-28 07:16:55',
 '2021-01-28 07:13:06',
 '2021-01-28 07:07:50',
 '2021-01-28 07:07:28',
 '2021-01-28 07:05:09',
 '2021-01-28 07:01:27',
 '2021-01-28 07:00:16',
 '2021-01-28 06:56:56',
 '2021-01-28 06:56:18',
 '2021-01-28 06:55:56',
 '2021-01-28 06:55:25',
 '2021-01-28 06:49:59',
 '2021-01-28 06:48:42',
 '2021-01-28 06:46:29',
 '2021-01-28 06:45:48',
 '2021-01-28 06:44:33',
 '2021-01-28 06:41:57',
 '2021-01-28 06:40:00',
 '2021-01-28 06:37:26',
 '2021-01-28 06:35:04',
 '2021-01-28 06:29:30',
 '2021-01-28 06:29:20',
 '2021-01-28 06:29:16',
 '2021-01-28 06:29:08',
 '2021-01-28 06:28:54',
 '2021-01-28 06:27:44',
 '2021-01-28 06:24:57',
 '2021-01-28 06:23:40',
 '2021-01-28 06:23:33',
 '2021-01-28 06:21:52',
 '2021-01-28 06:21:51',
 '2021-01-28 06:20:16',
 '2021-01-28 06:19:58',
 '2021-01-28 06:19:44',
 '2021-01-28 06:19:41',
 '2021-01-28 06:14:30',
 '2021-01-28 06:10:23',
 '2021-01-28 06:08:05',
 '2021-01-28 06:06:23',
 '2021-01-28 06:04:53',
 '2021-01-28 06:02:58',
 '2021-01-28 06:02:07',
 '2021-01-28 06:02:05',
 '2021-01-28 06:01:07',
 '2021-01-28 06:00:21',
 '2021-01-28 05:58:57',
 '2021-01-28 05:58:18',
 '2021-01-28 05:58:08',
 '2021-01-28 05:57:44',
 '2021-01-28 05:57:07',
 '2021-01-28 05:55:07',
 '2021-01-28 05:55:02',
 '2021-01-28 05:54:38',
 '2021-01-28 05:52:10',
 '2021-01-28 05:51:27',
 '2021-01-28 05:50:51',
 '2021-01-28 05:50:10',
 '2021-01-28 05:48:53',
 '2021-01-28 05:45:41',
 '2021-01-28 05:44:34',
 '2021-01-28 05:43:15',
 '2021-01-28 05:42:14',
 '2021-01-28 05:42:04',
 '2021-01-28 05:40:00',
 '2021-01-28 05:39:12',
 '2021-01-28 05:38:52',
 '2021-01-28 05:38:02',
 '2021-01-28 05:37:20',
 '2021-01-28 05:37:14',
 '2021-01-28 05:34:05',
 '2021-01-28 05:31:05',
 '2021-01-28 05:29:16',
 '2021-01-28 05:29:06',
 '2021-01-28 05:28:27',
 '2021-01-28 05:26:36',
 '2021-01-28 05:26:22',
 '2021-01-28 05:22:52',
 '2021-01-28 05:21:08',
 '2021-01-28 05:20:51',
 '2021-01-28 05:20:30',
 '2021-01-28 05:19:27',
 '2021-01-28 05:18:37',
 '2021-01-28 05:17:37',
 '2021-01-28 05:17:31',
 '2021-01-28 05:16:53',
 '2021-01-28 05:15:48',
 '2021-01-28 05:14:37',
 '2021-01-28 05:14:26',
 '2021-01-28 05:10:59',
 '2021-01-28 05:10:12',
 '2021-01-28 05:10:11',
 '2021-01-28 05:06:38',
 '2021-01-28 05:04:53',
 '2021-01-28 05:02:22',
 '2021-01-28 05:02:13',
 '2021-01-28 05:01:07',
 '2021-01-28 05:00:24',
 '2021-01-28 05:00:23',
 '2021-01-28 05:00:02',
 '2021-01-28 04:59:22',
 '2021-01-28 04:59:01',
 '2021-01-28 04:58:27',
 '2021-01-28 04:57:38',
 '2021-01-28 04:56:51',
 '2021-01-28 04:55:30',
 '2021-01-28 04:55:28',
 '2021-01-28 04:55:00',
 '2021-01-28 04:52:52',
 '2021-01-28 04:51:57',
 '2021-01-28 04:50:48',
 '2021-01-28 04:50:29',
 '2021-01-28 04:49:58',
 '2021-01-28 04:49:34',
 '2021-01-28 04:49:01',
 '2021-01-28 04:48:40',
 '2021-01-28 04:47:50',
 '2021-01-28 04:47:09',
 '2021-01-28 04:47:00',
 '2021-01-28 04:46:18',
 '2021-01-28 04:45:32',
 '2021-01-28 04:44:19',
 '2021-01-28 04:42:37',
 '2021-01-28 04:41:21',
 '2021-01-28 04:40:28',
 '2021-01-28 04:40:02',
 '2021-01-28 04:39:52',
 '2021-01-28 04:39:48',
 '2021-01-28 04:39:39',
 '2021-01-28 04:39:09',
 '2021-01-28 04:38:55',
 '2021-01-28 04:38:01',
 '2021-01-28 04:37:58',
 '2021-01-28 04:36:14',
 '2021-01-28 04:36:07',
 '2021-01-28 04:36:03',
 '2021-01-28 04:34:18',
 '2021-01-28 04:33:58',
 '2021-01-28 04:33:54',
 '2021-01-28 04:32:56',
 '2021-01-28 04:32:53',
 '2021-01-28 04:31:21',
 '2021-01-28 04:29:30',
 '2021-01-28 04:28:30',
 '2021-01-28 04:27:43',
 '2021-01-28 04:27:25',
 '2021-01-28 04:26:38',
 '2021-01-28 04:25:27',
 '2021-01-28 04:25:22',
 '2021-01-28 04:24:53',
 '2021-01-28 04:21:10',
 '2021-01-28 04:21:09',
 '2021-01-28 04:20:32',
 '2021-01-28 04:18:50',
 '2021-01-28 04:18:49',
 '2021-01-28 04:18:39',
 '2021-01-28 04:18:35',
 '2021-01-28 04:18:30',
 '2021-01-28 04:18:27',
 '2021-01-28 04:14:56',
 '2021-01-28 04:12:39',
 '2021-01-28 04:10:52',
 '2021-01-28 04:08:50',
 '2021-01-28 04:08:49',
 '2021-01-28 04:08:47',
 '2021-01-28 04:07:59',
 '2021-01-28 04:07:02',
 '2021-01-28 04:06:42',
 '2021-01-28 04:05:46',
 '2021-01-28 04:04:49',
 '2021-01-28 04:04:46',
 '2021-01-28 04:02:37',
 '2021-01-28 04:02:29',
 '2021-01-28 04:01:00',
 '2021-01-28 04:00:03',
 '2021-01-28 03:59:53',
 '2021-01-28 03:59:34',
 '2021-01-28 03:59:28',
 '2021-01-28 03:58:01',
 '2021-01-28 03:57:26',
 '2021-01-28 03:56:42',
 '2021-01-28 03:55:15',
 '2021-01-28 03:53:47',
 '2021-01-28 03:53:23',
 '2021-01-28 03:51:22',
 '2021-01-28 03:51:14',
 '2021-01-28 03:50:23',
 '2021-01-28 03:50:05',
 '2021-01-28 03:49:40',
 '2021-01-28 03:49:30',
 '2021-01-28 03:49:06',
 '2021-01-28 03:47:33',
 '2021-01-28 03:46:17',
 '2021-01-28 03:45:51',
 '2021-01-28 03:45:47',
 '2021-01-28 03:45:44',
 '2021-01-28 03:45:42',
 '2021-01-28 03:45:17',
 '2021-01-28 03:44:19',
 '2021-01-28 03:43:31',
 '2021-01-28 03:43:14',
 '2021-01-28 03:43:00',
 '2021-01-28 03:42:55',
 '2021-01-28 03:42:40',
 '2021-01-28 03:42:15',
 '2021-01-28 03:42:14',
 '2021-01-28 03:41:18',
 '2021-01-28 03:40:45',
 '2021-01-28 03:40:09',
 '2021-01-28 03:39:21',
 '2021-01-28 03:38:39',
 '2021-01-28 03:38:11',
 '2021-01-28 03:38:06',
 '2021-01-28 03:37:02',
 '2021-01-28 03:36:47',
 '2021-01-28 03:34:47',
 '2021-01-28 03:34:35',
 '2021-01-28 03:34:31',
 '2021-01-28 03:33:59',
 '2021-01-28 03:33:00',
 '2021-01-28 03:32:56',
 '2021-01-28 03:32:16',
 '2021-01-28 03:31:51',
 '2021-01-28 03:30:18',
 '2021-01-28 03:29:26',
 '2021-01-28 03:29:15',
 '2021-01-28 03:28:30',
 '2021-01-28 03:28:28',
 '2021-01-28 03:28:13',
 '2021-01-28 03:27:29',
 '2021-01-28 03:27:07',
 '2021-01-28 03:26:14',
 '2021-01-28 03:25:49',
 '2021-01-28 03:25:40',
 '2021-01-28 03:25:26',
 '2021-01-28 03:25:18',
 '2021-01-28 03:25:12',
 '2021-01-28 03:24:22',
 '2021-01-28 03:24:13',
 '2021-01-28 03:24:06',
 '2021-01-28 03:24:03',
 '2021-01-28 03:24:03',
 '2021-01-28 03:23:48',
 '2021-01-28 03:22:52',
 '2021-01-28 03:22:45',
 '2021-01-28 03:22:22',
 '2021-01-28 03:21:56',
 '2021-01-28 03:20:53',
 '2021-01-28 03:20:37',
 '2021-01-28 03:19:50',
 '2021-01-28 03:19:46',
 '2021-01-28 03:19:15',
 '2021-01-28 03:18:38',
 '2021-01-28 03:15:57',
 '2021-01-28 03:15:00',
 '2021-01-28 03:14:53',
 '2021-01-28 03:14:32',
 '2021-01-28 03:14:18',
 '2021-01-28 03:13:44',
 '2021-01-28 03:13:43',
 '2021-01-28 03:11:52',
 '2021-01-28 03:11:28',
 '2021-01-28 03:11:26',
 '2021-01-28 03:11:08',
 '2021-01-28 03:08:40',
 '2021-01-28 03:07:03',
 '2021-01-28 03:06:09',
 '2021-01-28 03:05:33',
 '2021-01-28 03:05:26',
 '2021-01-28 03:04:56',
 '2021-01-28 03:04:31',
 '2021-01-28 03:03:00',
 '2021-01-28 03:02:06',
 '2021-01-28 03:02:01',
 '2021-01-28 03:00:22',
 '2021-01-28 02:59:55',
 '2021-01-28 02:59:48',
 '2021-01-28 02:58:27',
 '2021-01-28 02:58:14',
 '2021-01-28 02:57:53',
 '2021-01-28 02:57:53',
 '2021-01-28 02:57:37',
 '2021-01-28 02:57:06',
 '2021-01-28 02:56:53',
 '2021-01-28 02:54:44',
 '2021-01-28 02:54:39',
 '2021-01-28 02:54:14',
 '2021-01-28 02:53:23',
 '2021-01-28 02:53:04',
 '2021-01-28 02:52:10',
 '2021-01-28 02:51:45',
 '2021-01-28 02:50:54',
 '2021-01-28 02:50:45',
 '2021-01-28 02:50:05',
 '2021-01-28 02:48:40',
 '2021-01-28 02:48:23',
 '2021-01-28 02:48:15',
 '2021-01-28 02:47:13',
 '2021-01-28 02:46:48',
 '2021-01-28 02:44:32',
 '2021-01-28 02:44:15',
 '2021-01-28 02:43:31',
 '2021-01-28 02:43:15',
 '2021-01-28 02:42:55',
 '2021-01-28 02:42:29',
 '2021-01-28 02:40:20',
 '2021-01-28 02:40:15',
 '2021-01-28 02:40:13',
 '2021-01-28 02:39:11',
 '2021-01-28 02:37:53',
 '2021-01-28 02:37:29',
 '2021-01-28 02:36:04',
 '2021-01-28 02:35:10',
 '2021-01-28 02:32:39',
 '2021-01-28 02:32:14',
 '2021-01-28 02:32:06',
 '2021-01-28 02:31:14',
 '2021-01-28 02:30:36',
 '2021-01-28 02:29:17',
 '2021-01-28 02:29:10',
 '2021-01-28 02:28:58',
 '2021-01-28 02:28:06',
 '2021-01-28 02:27:39',
 '2021-01-28 02:27:10',
 '2021-01-28 02:27:05',
 '2021-01-28 02:26:39',
 '2021-01-28 02:26:33',
 '2021-01-28 02:26:20',
 '2021-01-28 02:25:40',
 '2021-01-28 02:24:37',
 '2021-01-28 02:24:00',
 '2021-01-28 02:22:54',
 '2021-01-28 02:22:24',
 '2021-01-28 02:22:09',
 '2021-01-28 02:21:59',
 '2021-01-28 02:21:23',
 '2021-01-28 02:20:42',
 '2021-01-28 02:20:15',
 '2021-01-28 02:19:27',
 '2021-01-28 02:19:06',
 '2021-01-28 02:18:47',
 '2021-01-28 02:18:35',
 '2021-01-28 02:18:16',
 '2021-01-28 02:18:05',
 '2021-01-28 02:17:33',
 '2021-01-28 02:16:38',
 '2021-01-28 02:16:32',
 '2021-01-28 02:15:55',
 '2021-01-28 02:15:22',
 '2021-01-28 02:14:26',
 '2021-01-28 02:14:18',
 '2021-01-28 02:14:17',
 '2021-01-28 02:14:05',
 '2021-01-28 02:13:44',
 '2021-01-28 02:13:29',
 '2021-01-28 02:13:25',
 '2021-01-28 02:13:01',
 '2021-01-28 02:12:44',
 '2021-01-28 02:12:18',
 '2021-01-28 02:12:11',
 '2021-01-28 02:12:11',
 '2021-01-28 02:11:40',
 '2021-01-28 02:11:16',
 '2021-01-28 02:10:17',
 '2021-01-28 02:10:16',
 '2021-01-28 02:10:14',
 '2021-01-28 02:09:22',
 '2021-01-28 02:08:39',
 '2021-01-28 02:08:38',
 '2021-01-28 02:08:35',
 '2021-01-28 02:08:13',
 '2021-01-28 02:07:27',
 '2021-01-28 02:07:06',
 '2021-01-28 02:06:51',
 '2021-01-28 02:06:43',
 '2021-01-28 02:06:35',
 '2021-01-28 02:05:31',
 '2021-01-28 02:05:21',
 '2021-01-28 02:05:18',
 '2021-01-28 02:03:49',
 '2021-01-28 02:03:33',
 '2021-01-28 02:03:32',
 '2021-01-28 02:03:18',
 '2021-01-28 02:03:01',
 '2021-01-28 02:02:17',
 '2021-01-28 02:02:07',
 '2021-01-28 02:01:00',
 '2021-01-28 02:00:53',
 '2021-01-28 02:00:52',
 '2021-01-28 02:00:34',
 '2021-01-28 02:00:25',
 '2021-01-28 02:00:05',
 '2021-01-28 01:57:45',
 '2021-01-28 01:57:21',
 '2021-01-28 01:57:10',
 '2021-01-28 01:57:09',
 '2021-01-28 01:56:42',
 '2021-01-28 01:56:37',
 '2021-01-28 01:55:47',
 '2021-01-28 01:55:02',
 '2021-01-28 01:54:58',
 '2021-01-28 01:54:33',
 '2021-01-28 01:54:10',
 '2021-01-28 01:53:48',
 '2021-01-28 01:53:07',
 '2021-01-28 01:52:59',
 '2021-01-28 01:52:45',
 '2021-01-28 01:52:02',
 '2021-01-28 01:49:51',
 '2021-01-28 01:48:54',
 '2021-01-28 01:48:51',
 '2021-01-28 01:48:23',
 '2021-01-28 01:48:06',
 '2021-01-28 01:48:06',
 '2021-01-28 01:47:45',
 '2021-01-28 01:47:29',
 '2021-01-28 01:47:10',
 '2021-01-28 01:46:09',
 '2021-01-28 01:45:11',
 '2021-01-28 01:44:27',
 '2021-01-28 01:44:25',
 '2021-01-28 01:44:06',
 '2021-01-28 01:43:52',
 '2021-01-28 01:43:27',
 '2021-01-28 01:42:50',
 '2021-01-28 01:42:32',
 '2021-01-28 01:42:19',
 '2021-01-28 01:41:04',
 '2021-01-28 01:41:02',
 '2021-01-28 01:40:43',
 '2021-01-28 01:40:14',
 '2021-01-28 01:40:08',
 '2021-01-28 01:38:56',
 '2021-01-28 01:38:15',
 '2021-01-28 01:38:14',
 '2021-01-28 01:38:09',
 '2021-01-28 01:38:03',
 '2021-01-28 01:36:43',
 '2021-01-28 01:36:33',
 '2021-01-28 01:36:04',
 '2021-01-28 01:35:59',
 '2021-01-28 01:35:48',
 '2021-01-28 01:34:59',
 '2021-01-28 01:34:51',
 '2021-01-28 01:34:06',
 '2021-01-28 01:33:25',
 '2021-01-28 01:31:25',
 '2021-01-28 01:31:21',
 '2021-01-28 01:30:29',
 '2021-01-28 01:30:26',
 '2021-01-28 01:29:57',
 '2021-01-28 01:29:15',
 '2021-01-28 01:29:03',
 '2021-01-28 01:28:29',
 '2021-01-28 01:26:57',
 '2021-01-28 01:26:35',
 '2021-01-28 01:26:21',
 '2021-01-28 01:26:17',
 '2021-01-28 01:25:48',
 '2021-01-28 01:25:41',
 '2021-01-28 01:25:21',
 '2021-01-28 01:25:20',
 '2021-01-28 01:25:05',
 '2021-01-28 01:25:04',
 '2021-01-28 01:24:30',
 '2021-01-28 01:23:59',
 '2021-01-28 01:23:56',
 '2021-01-28 01:23:09',
 '2021-01-28 01:22:49',
 '2021-01-28 01:22:49',
 '2021-01-28 01:22:33',
 '2021-01-28 01:22:23',
 '2021-01-28 01:22:14',
 '2021-01-28 01:20:42',
 '2021-01-28 01:20:38',
 '2021-01-28 01:20:29',
 '2021-01-28 01:20:24',
 '2021-01-28 01:20:20',
 '2021-01-28 01:19:57',
 '2021-01-28 01:19:45',
 '2021-01-28 01:19:00',
 '2021-01-28 01:18:53',
 '2021-01-28 01:17:17',
 '2021-01-28 01:16:28',
 '2021-01-28 01:16:25',
 '2021-01-28 01:16:07',
 '2021-01-28 01:15:49',
 '2021-01-28 01:14:58',
 '2021-01-28 01:14:12',
 '2021-01-28 01:13:53',
 '2021-01-28 01:13:48',
 '2021-01-28 01:13:34',
 '2021-01-28 01:13:30',
 '2021-01-28 01:13:27',
 '2021-01-28 01:12:26',
 '2021-01-28 01:12:24',
 '2021-01-28 01:12:22',
 '2021-01-28 01:11:29',
 '2021-01-28 01:10:29',
 '2021-01-28 01:10:10',
 '2021-01-28 01:10:07',
 '2021-01-28 01:09:16',
 '2021-01-28 01:08:41',
 '2021-01-28 01:08:30',
 '2021-01-28 01:08:21',
 '2021-01-28 01:08:17',
 '2021-01-28 01:08:09',
 '2021-01-28 01:06:57',
 '2021-01-28 01:06:47',
 '2021-01-28 01:06:29',
 '2021-01-28 01:06:15',
 '2021-01-28 01:05:43',
 '2021-01-28 01:05:43',
 '2021-01-28 01:05:34',
 '2021-01-28 01:05:23',
 '2021-01-28 01:04:48',
 '2021-01-28 01:04:14',
 '2021-01-28 01:04:10',
 '2021-01-28 01:04:08',
 '2021-01-28 01:03:17',
 '2021-01-28 01:03:10',
 '2021-01-28 01:01:59',
 '2021-01-28 01:01:41',
 '2021-01-28 01:00:42',
 '2021-01-28 01:00:37',
 '2021-01-28 01:00:00',
 '2021-01-28 00:59:52',
 '2021-01-28 00:59:40',
 '2021-01-28 00:59:22',
 '2021-01-28 00:59:16',
 '2021-01-28 00:58:56',
 '2021-01-28 00:58:52',
 '2021-01-28 00:58:34',
 '2021-01-28 00:58:07',
 '2021-01-28 00:57:58',
 '2021-01-28 00:57:46',
 '2021-01-28 00:57:40',
 '2021-01-28 00:57:19',
 '2021-01-28 00:57:09',
 '2021-01-28 00:56:58',
 '2021-01-28 00:56:29',

In [24]:
def get_date(datetime):
    return re.findall(r'\d{4}-\d{2}-\d{2}',datetime)[0]

In [26]:
review_data['date']= review_data['date'].apply(get_date)

In [27]:
review_data.head()

,ReviewId,Business ID,user_id,useful,stars,date,review_text
0,lWC-xP3rd6obsecCYsGZRg,buF9druCkbuXLX526sGELQ,ak0TdVmGKo4pwqdJSTLwWw,3,4.0,2014-10-11,Apparently Prides Osteria had a rough summer a...
1,8bFej1QE5LXp4O05qjGqXA,RA4V8pr014UyUbDvI-LW2A,YoVfDbnISlW0f7abNQACIg,1,4.0,2015-07-03,This store is pretty good. Not as great as Wal...
2,NDhkzczKjLshODbqDoNLSg,_sS2LBIGNT5NQb6PD1Vtjw,eC5evKn1TWDyHCyQAwguUw,0,5.0,2013-05-28,I called WVM on the recommendation of a couple...
3,T5fAqjjFooT4V0OeZyuk1w,0AzLzHfOJgL7ROwhdww2ew,SFQ1jcnGguO0LYWnbbftAA,1,2.0,2010-01-08,I've stayed at many Marriott and Renaissance M...
4,sjm_uUcQVxab_EeLCqsYLg,8zehGz9jnxPqXtOc7KaJxA,0kA0PAJ8QFMeveQWHFqz2A,0,4.0,2011-07-28,The food is always great here. The service fro...

In [74]:
user_data

,user_id,review_count,yelping_since,useful,friends,average_stars,fans
0,q_QQ5kBBwlCcbL1s4NVK3g,1220,2005-03-14 20:26:35,15038,"xBDpTUbai0DXrvxCe3X16Q, 7GPNBO496aecrjJfW6UWtg...",3.85,1357
1,dIIKEfOgo0KqUfGQvGikPg,2136,2007-08-10 19:01:51,21272,"XPzYf9_mwG2eXYP2BAGSTA, 2LooM5dcIk2o01nftYdPIg...",4.09,1025
2,D6ErcUnFALnCQN4b1W_TlA,119,2007-02-07 15:47:53,188,"GfB6sC4NJQvSI2ewbQrDNA, jhZtzZNNZJOU2YSZ6jPlXQ...",3.76,16
3,JnPIjvC0cmooNDfsa9BmXg,987,2009-02-09 16:14:29,7234,"HQZPQhKMwRAyS6BCselVWQ, kP2U1s_sjQfHO9grxiyDTA...",3.77,420
4,37Hc8hr3cw0iHLoPzLK6Ow,495,2008-03-03 04:57:05,1577,"-Q88pZUcrfN0BLBDp-bkAQ, etPn4Pv1Gc4cRZjRgB_BOw...",3.72,47
...,...,...,...,...,...,...,...
2189444,9GN5U-Jh-2WF_4L0OrGdfA,6,2015-12-25 01:23:01,1,None,4.00,0
2189445,XE__rFfuZRdJkRa8nz4eiA,6,2015-12-09 22:21:27,3,None,2.33,0
2189446,fuC01HUN_tKPQd86S4EhkA,9,2015-03-06 06:30:45,8,None,3.00,0
2189447,sQ0PPwfoK-gpe4OVnfi4Eg,12,2018-06-12 02:15:47,3,None,3.38,0
2189448,OIOZBaJeLhhI9FcvwsDYvQ,3,2009-08-26 17:06:30,1,None,4.33,0

In [66]:
user_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2189449 entries, 0 to 2189448
Data columns (total 7 columns):
 #   Column         Dtype
---  ------         -----
 0   user_id        object
 1   review_count   int64
 2   yelping_since  object
 3   useful         int64
 4   friends        object
 5   average_stars  float64
 6   fans           int64
dtypes: float64(1), int64(3), object(3)
memory usage: 116.9+ MB

In [28]:
business_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160534 entries, 0 to 160533
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Business ID      160534 non-null  object
 1   Name             160534 non-null  object
 2   City             160534 non-null  object
 3   State            160534 non-null  object
 4   Postal_code      160424 non-null  object
 5   business_stars   160534 non-null  float64
 6   review_counts    160534 non-null  int64
 7   is_open          160534 non-null  int64
 8   RestaurantGroup  160534 non-null  object
 9   Categories       160419 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 12.2+ MB

In [67]:
# Combine review_data to the user_data
combined1 = review_data.merge(user_data, how = 'left', on ='user_id')

In [8]:

combined1.info(show_counts = True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8635402 entries, 0 to 8635401
Data columns (total 11 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   ReviewId       8635402 non-null  object
 1   Business ID    8635402 non-null  object
 2   user_id        8635402 non-null  object
 3   stars          8635402 non-null  float64
 4   review_text    8635400 non-null  object
 5   review_count   8635394 non-null  float64
 6   yelping_since  8635394 non-null  object
 7   useful         8635394 non-null  float64
 8   friends        8635394 non-null  object
 9   average_stars  8635394 non-null  float64
 10  fans           8635394 non-null  float64
dtypes: float64(5), object(6)
memory usage: 790.6+ MB

In [68]:
# Combined the business_data to the new combined dataset from above
combined = combined1.merge(business_data, how = 'left', on = 'Business ID')

In [31]:
#display the missing values in the combined dataset
print(combined.info(show_counts = True))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8635387 entries, 0 to 8635386
Data columns (total 20 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   ReviewId         8635387 non-null  object
 1   Business ID      8635387 non-null  object
 2   user_id          8635387 non-null  object
 3   useful           8635387 non-null  int64
 4   stars            8635387 non-null  float64
 5   date             8635387 non-null  object
 6   review_text      8635385 non-null  object
 7   review_count     8635379 non-null  float64
 8   friends          8635379 non-null  object
 9   average_stars    8635379 non-null  float64
 10  fans             8635379 non-null  float64
 11  Name             8630841 non-null  object
 12  City             8630841 non-null  object
 13  State            8630841 non-null  object
 14  Postal_code      8629156 non-null  object
 15  business_stars   8630841 non-null  float64
 16  review_counts    8630841 non-null  float64
 17  is_open          8630841 non-null  float64
 18  RestaurantGroup  8630841 non-null  object
 19  Categories       8629944 non-null  object
dtypes: float64(7), int64(1), object(12)
memory usage: 1.4+ GB
None

In [6]:
combined.head(10)

,ReviewId,Business ID,user_id,stars,review_text,review_count,yelping_since,useful,friends,average_stars,fans,Name,City,State,Postal_code,business_stars,review_counts,is_open,RestaurantGroup,Categories
0,lWC-xP3rd6obsecCYsGZRg,buF9druCkbuXLX526sGELQ,ak0TdVmGKo4pwqdJSTLwWw,4.0,Apparently Prides Osteria had a rough summer a...,63.0,2012-05-28 17:48:13,44.0,"CzluSWcP7d_xqmpGlXMWDg, We-UMzayIN32kO95l7dVeA...",4.30,2.0,Prides Osteria,Beverly,MA,01915,3.5,83.0,0.0,True,"Restaurants, Wine Bars, Nightlife, Farmers Mar..."
1,8bFej1QE5LXp4O05qjGqXA,RA4V8pr014UyUbDvI-LW2A,YoVfDbnISlW0f7abNQACIg,4.0,This store is pretty good. Not as great as Wal...,1674.0,2013-01-02 20:05:54,1664.0,"JUljrjhgO66NsHVaDfu0TQ, CRl3Eg-LFfxb2YTGjfpKnA...",3.88,125.0,Target,Framingham,MA,01701,3.0,65.0,1.0,None,"Department Stores, Optometrists, Home & Garden..."
2,NDhkzczKjLshODbqDoNLSg,_sS2LBIGNT5NQb6PD1Vtjw,eC5evKn1TWDyHCyQAwguUw,5.0,I called WVM on the recommendation of a couple...,1.0,2013-05-28 20:14:02,0.0,"xEdvxvSCmJMKAL7oZp1MhQ, HKsnvM0mRoelzlHQnPRPMg...",5.00,0.0,Willamette Valley Moving,Portland,OR,97210,5.0,277.0,1.0,None,"Home Services, Packing Services, Movers"
3,T5fAqjjFooT4V0OeZyuk1w,0AzLzHfOJgL7ROwhdww2ew,SFQ1jcnGguO0LYWnbbftAA,2.0,I've stayed at many Marriott and Renaissance M...,67.0,2009-07-10 23:36:10,34.0,L4WeaMJhwhycVPHGmgMApA,3.72,3.0,Renaissance Orlando at SeaWorld,Orlando,FL,32821,3.5,290.0,1.0,True,"Hotels, Hotels & Travel, Restaurants, Event Pl..."
4,sjm_uUcQVxab_EeLCqsYLg,8zehGz9jnxPqXtOc7KaJxA,0kA0PAJ8QFMeveQWHFqz2A,4.0,The food is always great here. The service fro...,12.0,2010-10-12 00:40:13,15.0,"ShheBOSa1yE_KSrQUSjDuQ, oRrZqvADpuvgcOiWfGPeYA...",4.15,2.0,Brasserie Ten Ten,Boulder,CO,80302,4.5,977.0,0.0,True,"Restaurants, French"
5,J4a2TuhDasjn2k3wWtHZnQ,xGXzsc-hzam-VArK6eTvtw,RNm_RWkcd02Li2mKPRe7Eg,1.0,"This place used to be a cool, chill place. Now...",22.0,2016-04-16 18:12:46,61.0,"nzp62FnO1grpR6_KdMQccQ, Gk-5EUiKPaPi4zmHGA_7ng...",2.48,1.0,The Burren,Somerville,MA,02144,3.5,499.0,1.0,True,"Restaurants, Bars, Irish Pub, Food, Pubs, Amer..."
6,28gGfkLs3igtjVy61lh77Q,EXOsmAB1s71WePlQk0WZrA,Q8c91v7luItVB0cMFF_mRA,2.0,"The setting is perfectly adequate, and the foo...",114.0,2006-03-30 10:20:09,256.0,"FeZU1LSQD2Fb_hl8gGXk5g, df5L9ZdKfiirFtoiIH1BbA...",3.60,5.0,Linwood Grill & BBQ Restaurant,Boston,MA,02215,2.5,14.0,0.0,True,Restaurants
7,9vqwvFCBG3FBiHGmOHMmiA,DbXHNl890xSXNiyRczLWAg,XGkAG92TQ3MQUKGX9sLUhw,5.0,Probably one of the better breakfast sandwiche...,3.0,2013-06-10 01:37:39,1.0,None,3.67,0.0,Orlando Meats,Winter Park,FL,32789,4.5,187.0,1.0,False,"Butcher, Brazilian, Argentine, Restaurants, Sa..."
8,2l_TDrQ7p-5tANOyiOlkLQ,mD-A9KOWADXvfrZfwDs-jw,LWUnzwK0ILquLLZcHHE1Mw,4.0,I am definitely a fan of Sports Authority. Th...,518.0,2010-12-20 03:07:16,545.0,"Ub3VU4TLZL7cpaDUvOjYTw, mMzJqiC39EFqIz0pn7XF_g...",4.51,20.0,Sports Authority,Altamonte Springs,FL,32714,3.0,10.0,0.0,None,"Outdoor Gear, Sports Wear, Fashion, Shopping, ..."
9,KKVFopqzcVfcubIBxmIjVA,EEHhKSxUvJkoPSzeGKkpVg,99RsBrARhhx60UnAC4yDoA,5.0,I work in the Pru and this is the most afforda...,1.0,2010-01-31 00:47:25,0.0,None,5.00,0.0,Boston Chowda Co,Boston,MA,02199,3.5,110.0,0.0,True,"Sandwiches, Seafood, Soup, Restaurants, Fast Food"

## 1.2 Select only opened-restaurant businesses

In [69]:
rest_df = combined.loc[(combined['RestaurantGroup'] == 'True') & (combined['is_open'] == 1),:]

In [73]:
rest_df.info(show_counts = True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3774475 entries, 3 to 8635384
Data columns (total 22 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   ReviewId         3774475 non-null  object
 1   Business ID      3774475 non-null  object
 2   user_id          3774475 non-null  object
 3   useful_x         3774475 non-null  int64
 4   stars            3774475 non-null  float64
 5   date             3774475 non-null  object
 6   review_text      3774474 non-null  object
 7   review_count     3774472 non-null  float64
 8   yelping_since    3774472 non-null  object
 9   useful_y         3774472 non-null  float64
 10  friends          3774472 non-null  object
 11  average_stars    3774472 non-null  float64
 12  fans             3774472 non-null  float64
 13  Name             3774475 non-null  object
 14  City             3774475 non-null  object
 15  State            3774475 non-null  object
 16  Postal_code      3774437 non-null  object
 17  business_stars   3774475 non-null  float64
 18  review_counts    3774475 non-null  float64
 19  is_open          3774475 non-null  float64
 20  RestaurantGroup  3774475 non-null  object
 21  Categories       3774475 non-null  object
dtypes: float64(8), int64(1), object(13)
memory usage: 662.3+ MB

In [70]:
rest_df.rename

Index(['ReviewId', 'Business ID', 'user_id', 'useful_x', 'stars', 'date',
       'review_text', 'review_count', 'yelping_since', 'useful_y', 'friends',
       'average_stars', 'fans', 'Name', 'City', 'State', 'Postal_code',
       'business_stars', 'review_counts', 'is_open', 'RestaurantGroup',
       'Categories'],
      dtype='object')

In [71]:
def get_2020_year(date):
    match = re.search(r'2020-\d{2}-\d{2}',date)
    if match:
        return True
    else:
        return False

In [72]:
bools = rest_df['date'].apply(get_2020_year)

In [75]:
rest_df_update = rest_df.loc[bools,['ReviewId', 'Business ID', 'user_id', 'useful_x', 'stars', 'date',
       'review_text', 'review_count', 'yelping_since',
       'average_stars', 'Name', 'City', 'State', 'Postal_code',
       'business_stars', 'review_counts']]

In [78]:
rest_df_update=rest_df_update.rename(columns = {'useful_x':'useful','review_count':'user_review_counts','review_counts':'biz_review_counts'})

In [79]:
rest_df_update

,ReviewId,Business ID,user_id,useful,stars,date,review_text,user_review_counts,yelping_since,average_stars,Name,City,State,Postal_code,business_stars,biz_review_counts
589521,euyonIoTGp6tMa4ATcZsjQ,6my4VxfCGHhRIOkSjkOpAg,M0uuqU5amRW22fUCSrWiXQ,0,1.0,2020-01-01,I'm giving one star not because the food was b...,4.0,2014-05-21 17:16:40,4.00,Papa Murphy's,Tualatin,OR,97062,3.0,20.0
589522,FaOPA8Wg7IL9P9cRPVfg2A,_HjtaT4TMHwOoGG_pZmk1A,IjkcZH5qcb17yn4fCc8pvg,0,5.0,2020-01-02,Torchy's got nothing on this place. First time...,8.0,2013-11-03 21:26:36,5.00,Macho Taco,Austin,TX,78748,4.5,222.0
589524,AueHLY8Z4k4CYYHohIsdFg,UAtX7xmIfdd1W2Pebf6NWg,USEM1lAYDJIwkGVxkSfdVw,2,3.0,2020-01-01,Chill dive bar that was around the corner from...,585.0,2014-06-26 13:05:57,4.14,Sidebar Boston,Boston,MA,02108,3.5,240.0
589549,cZoQ8fzRaBD3EbICD9osWg,-dNzrtdgR9v5kbqxw0ZKoA,wSaW5syvPtC2yGF0GaGlCw,0,5.0,2020-01-13,"Love this place! Fantastic service, excellent ...",38.0,2009-12-26 20:36:41,2.98,Gabriela's Downtown,Austin,TX,78702,4.0,490.0
589553,AIa6lLSksITpd__eaxTDSg,XbB45YpsaI2qg2s3qBfYyg,4cViV1o3IsIDqOBFhe8cig,0,5.0,2020-01-15,My favorite authentic Italian place to visit. ...,1.0,2019-05-12 13:34:33,5.00,Antica Pizzeria & mozzarella Bar,Altamonte Springs,FL,32714,4.5,180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8635372,oabuTmGpHquA4sc4C0DatQ,Qmq4gr5Mmo2oIVejag48PA,tsSyIyhRp37fDpN78q3crw,4,4.0,2020-09-13,This place serves amazingly tasty gluten free ...,395.0,2013-07-17 01:09:03,3.29,Kerbey Lane Cafe - Central,Austin,TX,78731,4.0,1297.0
8635375,_DF1buntOtoP0vqrZMls1g,CnuJ9rh9xvKJ3EaCo1xIOw,nRRvAmz3K9jSvenAf_H4wg,6,5.0,2020-10-02,I am so glad I was finally able to eat at domu...,86.0,2016-07-16 19:14:59,4.40,Domu,Orlando,FL,32803,4.0,1180.0
8635376,SZwokVY7CHjgAgG8qCxebQ,O1pWzMvVmBomQUaZ3aUlLw,nVN20tunCTGzxSXrhD9K6Q,1,5.0,2020-12-30,This place is legit! I had the Funky Monkey Fr...,403.0,2017-08-30 14:03:24,3.65,"Snooze, an A.M. Eatery E. Austin",Austin,TX,78702,4.0,103.0
8635377,t_yYdoreY7Nbusx7lKGRlg,HpiE8X3s8xRRRihjp7_IMA,wekex6_bNxkj2G4XQB5Inw,0,5.0,2020-11-24,this place is amazing! we ate tiramisu and str...,3.0,2014-08-27 12:01:25,4.50,Mia's Italian Kitchen,Orlando,FL,32819,4.5,532.0
8635384,WCDbBwtgk69s9TjLcEab8A,_qkEX2cEPXuGmpa_bunJ2Q,lHXnu8hjfCQzltV3jYVB7Q,1,2.0,2020-02-21,This is my second experience at Salad Express ...,52.0,2015-03-07 04:24:54,4.05,Salad Express,Atlanta,GA,30324,4.0,131.0

In [80]:
rest_df_update.to_csv('restaurant_dataset_updated.csv',mode = 'w',encoding= 'utf-8')